base:
  project: AirBnb-project
database:
  data: database/secure-connect-airbnb.zip
Credentials:
  Client_id: GUIuEtGFJZyhLRdIyFaymbvE
  Client_secret: xE2XLTL32wBenKZtBctt8Moym-tLbyuKU0_zWkYIRE0XwlKNqi+jNdE8QK21Q0nFQBi76a6.NiA+ibFu81G53-iBKuHKNjGCAjZ8ATbdymaP3iCO1J0N__M2Re,7RMEo

Data:
  Raw: Data/Raw/airbnb.csv
  Processed: Data/processed/airbnb.csv