base:
  project: AirBnb-project
database:
  data: database/secure-connect-airbnb.zip
Credentials:
  Client_id: GUIuEtGFJZyhLRdIyFaymbvE
  Client_secret: xE2XLTL32wBenKZtBctt8Moym-tLbyuKU0_zWkYIRE0XwlKNqi+jNdE8QK21Q0nFQBi76a6.NiA+ibFu81G53-iBKuHKNjGCAjZ8ATbdymaP3iCO1J0N__M2Re,7RMEo

Data:
  Raw: Data/Raw/airbnb.csv
  Processed: Data/processed/airbnb.csv
  Evaluated: Data/evaluated/airbnb.csv
  Final: Data/final/airbnb.csv

models:
  Labelencoder:
    city: models/LabelEncoder/city.pkl
    property_type: models/LabelEncoder/property_type.pkl
    room_type: models/LabelEncoder/room_type.pkl
    cancellation_policy: models/LabelEncoder/cancellation_policy.pkl
  xgboost: models/xgboost/xgboost.pkl
  sc: models/xgboost/sc.pkl

reports:
  scores: report/scores.json
  params: report/params.json